### ISSUE TITLE
dhcpd and iptables missing

### ISSUE THREAD

**Issue by jan-eckhoff** [insberr/pi-internet-bridge#3]
Hi Jonah,

THANK YOU for providing this update to all those slightly but annoyingly non-working identical tutorials out there.
I found it precisely because I ran into the same issues as you did, and sure enough, your fixes worked.
I can now route my backup mobile internet router's wifi signal into my main router's LAN1 port, so we can continue to use our wifi as usual, even though our main internet is currently down.

Two things that all those tutorials assumed as a given, but weren't present on my freshly installed Raspberry Pi OS: dhcpd and iptables.
So in the spirit of completeness, we could consider adding those as explicit requirements or just add the appropriate apt-get commands before we dive into the respective config files.

Again, thank you :-)

Greetings from Hamburg, Germany
Jan

**Comment by insberr** [comment]
Hello Jan,

I am glad you found my fixes helpful! Sorry for the late reply haha.
I can certainly add them (you are also welcome to create a pull request, I might forget to do it myself).

Jonah

**Comment by insberr** [comment]
Added a note of this in step 2.
